name: Retgas CD - Deploy Android

on:
  push:
    branches:
      - main
      
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      - name: Read last version tag 
        run: |
          git fetch --prune --unshallow
          echo "CURRENT_VERSION=$(git describe --tags `git rev-list --tags --grep=test_android --max-count=1`)" >> "$GITHUB_ENV"       
      - name: Set current build version
        run: echo "CURRENT_BUILD_VERSION=$(echo ${{ env.CURRENT_VERSION }} | cut -d 'test_android_' -f 2 | cut -d'+' -f 1)" >> "$GITHUB_ENV"
      - name: Set current build version patch
        run: echo "CURRENT_BUILD_VERSION_PATCH=$(echo ${{ env.CURRENT_BUILD_VERSION }} | cut -d'.' -f 3)" >> "$GITHUB_ENV" 
      - name: Set current build version major and minor
        run: echo "CURRENT_BUILD_VERSION_MAJOR_MINOR=$(echo ${{ env.CURRENT_BUILD_VERSION }} | cut -d'.' -f 1,2)" >> "$GITHUB_ENV"
      - name: Increment version patch
        run: echo "CURRENT_BUILD_VERSION_PATCH=$((${{ env. CURRENT_BUILD_VERSION_PATCH }}+1))" >> "$GITHUB_ENV"
      - name: Set next build version
        run: echo "NEXT_BUILD_VERSION=$(echo ${{ env. CURRENT_BUILD_VERSION_MAJOR_MINOR }}.${{ env.CURRENT_BUILD_VERSION_PATCH }})" >> "$GITHUB_ENV"
      - name: Set current build number
        run: echo "NEXT_BUILD_NUMBER=$(echo ${{ env.CURRENT_VERSION }} | cut -d'test_android_' -f 2 | cut -d'+' -f 2)" >> "$GITHUB_ENV"
      - name: Set next build number
        run: echo "NEXT_BUILD_NUMBER=$((${{ env.NEXT_BUILD_NUMBER }}+1))" >> "$GITHUB_ENV"
      - name: Print next build number tag
        run: echo test_android_${{ env.NEXT_BUILD_VERSION }}+${{ env.NEXT_BUILD_NUMBER }}
      - name: Create new git version tag
        run: echo "NEXT_GIT_TAG='test_android_${{ env.NEXT_BUILD_VERSION }}+${{ env.NEXT_BUILD_NUMBER }}'" >> "$GITHUB_ENV"
      - name: Update git version tag 
        run: git tag $NEXT_GIT_TAG
      - name: Push git tag 
        run: git push origin $NEXT_GIT_TAG
